seed: 0
num_envs: 2048
board_size: 10
device: cuda
out_device: cuda  # Changed from cpu to cuda to avoid GPU->CPU->GPU transfers
run_dir:

augment: false

epochs: 5000
steps: 256
save_interval: 100
eval_interval: 20  # Evaluate every 20 epochs (set to 1000 to disable during development)
eval_num_envs: 1024  # Use fewer environments for faster evaluation (default: 512)


black_checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/0.pt
white_checkpoint: pretrained_models/${board_size}_${board_size}/${algo.name}/1.pt

wandb:
  group: ${board_size}_${board_size}_${algo.name}_InRL
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
  - baseline: ppo
